#!/usr/bin/env python3
"""Write the ground-truth JSON sidecar for every fixture.

Run manually from the repo root:

    uv run --no-sync python tests/paper/fixtures_authoring/write_sidecars.py

The values below are the corpus ground truth: derived from the authored XML,
cross-checked against a raw-XML facts extraction of every built fixture, and
frozen by MANIFEST.sha256 alongside the fixtures themselves. Editing a value
here (and re-running) is a deliberate, reviewed act.

The sidecar schema is exactly these six keys: fixture, provenance, features,
ground_truth, verified_by, date.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from tests.paper.harness.paths import FIXTURES_DIR  # noqa: E402

SIDECAR_DATE = "2026-07-07"
VERIFIED_BY = "UNVERIFIED — agent-authored (Claude), machine-cross-checked; human sign-off pending"

GENERATED_PROVENANCE = {
    "app": "paper-docx tests/paper/fixtures_authoring/build_fixtures.py",
    "version": "paper-docx 0.1.0 (python-docx 1.2.0 base)",
    "notes": (
        "Generated by this repo's own authoring code: python-docx assembles the base"
        " document; tracked changes, content controls, text box, footnotes/endnotes"
        " and numbering definitions are hand-written ECMA-376 XML. Deterministic"
        " rebuild (fixed dates, fixed zip timestamps)."
    ),
}


def lo_provenance(stem: str, extra: str = "") -> Dict[str, str]:
    notes = (
        f"Headless `soffice --convert-to docx` round-trip of"
        f" generated/feature-isolated/{stem}.docx; LibreOffice re-authored every"
        f" part, so markup shapes are LibreOffice's own."
    )
    if extra:
        notes += " " + extra
    return {"app": "LibreOffice", "version": "26.2.4.2", "notes": notes}


RATE_TEXT = (
    "Consulting rate: $75–100/hr on a “full-service” basis"
    " — travel time billed at $37.50/hr."
)
NBSP_TEXT = "Net 30 payment terms apply, with a 10 % late surcharge."

TRACKED_GROUND_TRUTH: Dict[str, Any] = {
    "tracked_insertions": {
        "count": 2,
        "authors": ["Alice Editor", "Bob Reviewer"],
        "dates": ["2026-06-01T09:30:00Z", "2026-06-02T14:45:00Z"],
        "inserted_texts": [
            "forty-seven",
            "This whole sentence was inserted with tracking on.",
        ],
    },
    "tracked_deletions": {
        "count": 1,
        "authors": ["Bob Reviewer"],
        "dates": ["2026-06-02T14:45:00Z"],
        "deleted_texts": ["forty-two"],
    },
    "revised_paragraph": {
        "visible_text_current": "The quarterly total was forty-seven units.",
        "visible_text_original": "The quarterly total was forty-two units.",
    },
}

COMMENTS_GROUND_TRUTH: Dict[str, Any] = {
    "comments": [
        {
            "author": "Alice Editor",
            "initials": "AE",
            "date": "2026-06-03T10:15:00Z",
            "text": "Please double-check this figure.",
            "anchor_paragraph_text": "This paragraph carries the first comment.",
        },
        {
            "author": "Bob Reviewer",
            "initials": "BR",
            "date": "2026-06-03T10:15:00Z",
            "text": "Approved as written.",
            "anchor_paragraph_text": "A second paragraph with another comment target.",
        },
    ],
}

CONTENT_CONTROL_GROUND_TRUTH: Dict[str, Any] = {
    "block_control": {
        "alias": "ClauseBlock",
        "tag": "clause-block-1",
        "text": "Text inside a block-level content control.",
    },
    "inline_control": {
        "alias": "InlineField",
        "tag": "inline-field-1",
        "text": "controlled text",
        "host_paragraph_text": "Inline control follows: controlled text and text after it.",
    },
    "sdt_count": 2,
}

FOOTNOTES_GROUND_TRUTH: Dict[str, Any] = {
    "footnote": {"id": 1, "text": " The footnote body text, hand-authored."},
    "endnote": {"id": 1, "text": " The endnote body text, hand-authored."},
    "note_texts_start_with_preserved_space": True,
    "reference_paragraph_texts": [
        "This sentence carries a footnote reference.",
        "This sentence carries an endnote reference.",
    ],
}

HDRFTR_GROUND_TRUTH: Dict[str, Any] = {
    "section_count": 2,
    "section1": {
        "header_text": "Header for section one",
        "footer_text": "Footer for section one",
        "first_page_header_text": "First-page header for section one",
        "different_first_page": True,
    },
    "section2": {
        "header_text": "Header for section two",
        "footer_text": "Footer for section two",
    },
}

TABLE_GROUND_TRUTH: Dict[str, Any] = {
    "outer_table": {"rows": 3, "cols": 3},
    "horizontal_merge": {"row": 0, "merged_grid_cols": [0, 1], "grid_span_count": 1},
    "vertical_merge": {"grid_col": 2, "rows": [1, 2], "v_merge_count": 2},
    "nested_table": {
        "host_cell": {"row": 2, "col": 0},
        "rows": 2,
        "cols": 2,
        "cell_texts": ["N00", "N01", "N10", "N11"],
    },
}

NUMBERING_GROUND_TRUTH: Dict[str, Any] = {
    "custom_definition": {
        "num_id": 42,
        "abstract_num_id": 90,
        "levels": [
            {"ilvl": 0, "num_fmt": "decimal", "lvl_text": "%1."},
            {"ilvl": 1, "num_fmt": "lowerLetter", "lvl_text": "%2)"},
        ],
    },
    "numbered_paragraphs": [
        {"text": "First numbered item", "ilvl": 0, "num_id": 42},
        {"text": "Second numbered item", "ilvl": 0, "num_id": 42},
        {"text": "Nested lettered item", "ilvl": 1, "num_id": 42},
    ],
}

FRAGMENTED_GROUND_TRUTH: Dict[str, Any] = {
    "rate_paragraph": {
        "text": RATE_TEXT,
        "run_count": 8,
        "run_texts": [
            "Consulting rate: ",
            "$75",
            "–",
            "100/hr",
            " on a ",
            "“full-",
            "service”",
            " basis — travel time billed at $37.50/hr.",
        ],
        "bold_run_indices": [1, 2, 3],
        "italic_run_indices": [5, 6],
    },
    "nbsp_paragraph_text": NBSP_TEXT,
    "special_characters": {
        "en_dash": "–",
        "em_dash": "—",
        "left_double_quote": "“",
        "right_double_quote": "”",
        "no_break_space": " ",
    },
}

MINIMAL_GROUND_TRUTH: Dict[str, Any] = {
    "paragraphs": [
        {"text": "Minimal Clean Document", "style": "Heading1"},
        {"text": "First body paragraph with perfectly ordinary text."},
        {"text": "Second body paragraph, equally unremarkable."},
    ],
}

TRACKED_FEATURES = ["tracked-insertion", "tracked-deletion", "two-authors", "del-text"]
COMMENT_FEATURES = ["comments", "comment-reference-range", "comment-metadata"]
SDT_FEATURES = ["content-control-block", "content-control-inline"]
TEXTBOX_FEATURES = ["textbox", "wps-drawing"]
NOTES_FEATURES = ["footnotes", "endnotes", "note-references"]
HDRFTR_FEATURES = ["multiple-sections", "headers", "footers", "first-page-header"]
TABLE_FEATURES = [
    "table",
    "merged-cells-horizontal",
    "merged-cells-vertical",
    "nested-table",
]
NUMBERING_FEATURES = ["custom-numbering-definition", "numbering-references", "multilevel-list"]
FRAGMENTED_FEATURES = [
    "fragmented-runs",
    "smart-quotes",
    "en-dash",
    "em-dash",
    "no-break-space",
    "preserved-spaces",
    "formatting-transitions",
]


def sidecar(
    relpath: str,
    provenance: Dict[str, str],
    features: List[str],
    ground_truth: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        "fixture": Path(relpath).name,
        "provenance": provenance,
        "features": features,
        "ground_truth": ground_truth,
        "verified_by": VERIFIED_BY,
        "date": SIDECAR_DATE,
    }


MOVED_TEXT = "The indemnity clause relocated by tracked move."

MOVES_GROUND_TRUTH: Dict[str, Any] = {
    "move": {
        "author": "Alice Editor",
        "date": "2026-06-01T09:30:00Z",
        "name": "move1",
        "text": MOVED_TEXT,
        "move_from_ids": [61, 62],
        "move_to_ids": [63, 64],
    },
    "visible_text_current_contains_moved_text_times": 1,
    "visible_text_original_contains_moved_text_times": 1,
}

FORMAT_CHANGES_GROUND_TRUTH: Dict[str, Any] = {
    "run_property_change": {
        "author": "Bob Reviewer",
        "date": "2026-06-02T14:45:00Z",
        "now": "bold",
        "was": "plain",
        "text": "This text was bolded with tracking on.",
    },
    "paragraph_property_change": {
        "author": "Bob Reviewer",
        "date": "2026-06-02T14:45:00Z",
        "now": "centered",
        "was": "default",
        "text": "This paragraph was centered with tracking on.",
    },
    "format_change_count": 2,
}

FIELDS_GROUND_TRUTH: Dict[str, Any] = {
    "simple_field": {"instr": "DATE", "cached_result": "June 1, 2026"},
    "complex_field": {"instr": "PAGEREF _RefAnchor", "cached_result": "14"},
    "field_count": 2,
    "visible_text_includes_results": True,
}

PLACEHOLDER_GROUND_TRUTH: Dict[str, Any] = {
    "control": {
        "alias": "ClientName",
        "tag": "client-name",
        "showing_placeholder": True,
        "placeholder_text": "Click or tap here to enter text.",
        "placeholder_style": "PlaceholderText",
    },
}

BOOKMARKS_GROUND_TRUTH: Dict[str, Any] = {
    "named_bookmark": {"name": "DefinedTerm", "text": "the Master Agreement"},
    "point_bookmarks": ["_GoBack"],
    "host_paragraph_text": "See the Master Agreement for definitions.",
}

NOISY_MARKUP_GROUND_TRUTH: Dict[str, Any] = {
    "proof_err_count": 2,
    "comment": {"author": "Alice Editor", "text": "Noise-tolerance target."},
    "point_bookmarks": ["_GoBack"],
    "paragraph_texts": [
        "Paragrah with a spelling issue.",
        "This clause carries a reviewer comment.",
        "Paragraph after the noisy ones.",
    ],
}

MOVES_FEATURES = ["tracked-move", "move-range-markers"]
FORMAT_CHANGE_FEATURES = ["tracked-format-change", "rpr-change", "ppr-change"]
FIELDS_FEATURES = ["fields", "simple-field", "complex-field", "field-cached-result"]
PLACEHOLDER_FEATURES = ["content-control-placeholder", "showing-plc-hdr"]
BOOKMARK_FEATURES = ["bookmarks", "point-bookmark"]
NOISY_FEATURES = ["proof-err", "comment-anchors", "point-bookmark"]
TOC_FIELD_FEATURES = ["complex-field", "multi-paragraph-field", "toc-shape"]

TOC_FIELD_GROUND_TRUTH = {
    "field": {
        "instr": "TOC",
        "spans_paragraphs": 3,
        "entry_texts": [
            "Chapter One entry\t4",
            "Chapter Two entry\t9",
            "Chapter Three entry\t14",
        ],
    },
    "all_entry_paragraphs_are_field_content": True,
}

# -- redline-pipeline fixtures ----------------------------------------------

ROW_REVISION_FEATURES = ["tracked-row-insert", "tracked-row-delete", "row-revision-marks"]
RICH_FORMAT_FEATURES = FORMAT_CHANGE_FEATURES + [
    "paragraph-mark-format-change",
    "rich-stored-properties",
]
MERGE_FEATURES = [
    "paragraph-mark-deletion",
    "paragraph-mark-insertion",
    "tracked-merge",
    "tracked-split",
]

ROW_REVISIONS_GROUND_TRUTH: Dict[str, Any] = {
    "header_row": ["Item", "Amount"],
    "inserted_row": {
        "author": "Alice Editor",
        "marker": "w:trPr/w:ins",
        "cells": ["Filing fee", "$100"],
    },
    "deleted_row": {
        "author": "Bob Reviewer",
        "marker": "w:trPr/w:del",
        "cells": ["Old charge", "$50"],
    },
    "rows_after_accept_all": [["Item", "Amount"], ["Filing fee", "$100"]],
    "rows_after_reject_all": [["Item", "Amount"], ["Old charge", "$50"]],
}

FORMAT_CHANGES_RICH_GROUND_TRUTH: Dict[str, Any] = {
    "run_property_change": {
        "author": "Bob Reviewer",
        "now": "bold",
        "was": "italic, half-point size 28",
        "text": "Delivery follows the schedule in Exhibit A.",
    },
    "paragraph_property_change": {
        "author": "Bob Reviewer",
        "now": "centered",
        "was": "right-aligned",
        "text": "This paragraph was right-aligned before re-centering.",
    },
    "paragraph_mark_change": {
        "author": "Bob Reviewer",
        "now": "bold paragraph mark",
        "was": "plain paragraph mark",
        "text": "The paragraph mark itself was re-formatted.",
    },
    "format_change_count": 3,
}

PARAGRAPH_MERGE_GROUND_TRUTH: Dict[str, Any] = {
    "deleted_mark": {
        "author": "Bob Reviewer",
        "first_paragraph": "This sentence continues ",
        "second_paragraph": "onto the following line.",
        "accept_merges_to": "This sentence continues onto the following line.",
    },
    "inserted_mark": {
        "author": "Alice Editor",
        "first_paragraph": "A tracked split divides ",
        "second_paragraph": "this once-single sentence.",
        "reject_merges_to": "A tracked split divides this once-single sentence.",
    },
}


def protection_ground_truth(edit: str) -> Dict[str, Any]:
    return {
        "document_protection": {"edit": edit, "enforcement": True, "password": None},
        "inline_control_tag": "inline-field-1",
        "advisory_not_security": True,
        "body_paragraph_count": 3,
    }


MULTIROUND_MOVED_TEXT = "The indemnity clause shall survive termination of this agreement."

MULTIROUND_GROUND_TRUTH: Dict[str, Any] = {
    "authors": {
        "Alice Editor": "round 1: paragraph move, row insert, tracked split, signature insertion",
        "Bob Reviewer": "round 2: format changes, row delete, paragraph merge, comment",
    },
    "revision_features": [
        "whole-paragraph move pair mrMove1 with paragraph-mark stamps",
        "rPrChange with empty and with rich stored properties",
        "pPrChange with rich stored properties",
        "tracked row insert and row delete",
        "paragraph merge (deleted mark) and split (inserted mark)",
        "comment anchored inside a tracked insertion",
    ],
    "moved_text": MULTIROUND_MOVED_TEXT,
    "comment": {
        "author": "Bob Reviewer",
        "text": "Confirm the execution venue.",
        "anchored_inside_insertion": True,
    },
    "accepted_ground_truth": "generated/redline/multiround-accepted.docx",
}

MULTIROUND_ACCEPTED_GROUND_TRUTH: Dict[str, Any] = {
    "derivation": (
        "multiround.docx with every revision applied, hand-computed to Word's"
        " Accept All semantics"
    ),
    "revision_count": 0,
    "body_paragraph_texts": [
        "Engagement letter, revised across two rounds.",
        "This agreement is made between the parties.",
        "Middle paragraph between the move sites.",
        MULTIROUND_MOVED_TEXT,
        "Payment is due within thirty days of invoice.",
        "Delivery follows the schedule in Exhibit A.",
        "This sentence continues onto the following line.",
        "A tracked split divides ",
        "this once-single sentence.",
        "Signed at the offices of the Client.",
        "Closing paragraph after all tracked activity.",
    ],
    "table_rows": [["Item", "Amount"], ["Filing fee", "$100"]],
    "comment_survives_resolution": True,
}

COMPARE_ORIGINAL_GROUND_TRUTH: Dict[str, Any] = {
    "role": "compare-pair original (edited with tracking OFF into compare-revised.docx)",
    "revision_count": 0,
    "headings": ["Service Agreement", "Fees", "Confidentiality"],
    "table_rows": [["Service", "Rate"], ["Advisory", "$200"], ["Drafting", "$150"]],
}

COMPARE_REVISED_GROUND_TRUTH: Dict[str, Any] = {
    "role": "compare-pair revised",
    "revision_count": 0,
    "delta_from_original": [
        "reworded: 'consulting services' -> 'consulting and advisory services'",
        "deleted: 'The consultant will deliver monthly progress reports.'",
        "reworded: 'thirty days notice' -> 'sixty days notice'",
        "Confidentiality section moved ahead of Fees",
        "reworded: 'one percent' -> 'one and a half percent'",
        "added: 'A retainer of one thousand dollars is due on signing.'",
        "table cell changed: Advisory $200 -> $250",
    ],
    "headings": ["Service Agreement", "Confidentiality", "Fees"],
    "table_rows": [["Service", "Rate"], ["Advisory", "$250"], ["Drafting", "$150"]],
}


SIDECARS: Dict[str, Dict[str, Any]] = {
    # -- generated bucket ---------------------------------------------------
    "generated/minimal-clean/minimal.docx": sidecar(
        "minimal.docx",
        GENERATED_PROVENANCE,
        ["minimal-clean", "heading", "plain-paragraphs"],
        MINIMAL_GROUND_TRUTH,
    ),
    "generated/feature-isolated/tracked-ins-del.docx": sidecar(
        "tracked-ins-del.docx",
        GENERATED_PROVENANCE,
        TRACKED_FEATURES,
        TRACKED_GROUND_TRUTH,
    ),
    "generated/feature-isolated/comments.docx": sidecar(
        "comments.docx",
        GENERATED_PROVENANCE,
        COMMENT_FEATURES,
        COMMENTS_GROUND_TRUTH,
    ),
    "generated/feature-isolated/content-control.docx": sidecar(
        "content-control.docx",
        GENERATED_PROVENANCE,
        SDT_FEATURES,
        CONTENT_CONTROL_GROUND_TRUTH,
    ),
    "generated/feature-isolated/textbox.docx": sidecar(
        "textbox.docx",
        GENERATED_PROVENANCE,
        TEXTBOX_FEATURES,
        {
            "textbox_visible_texts": ["Text living inside the text box."],
            "raw_txbx_content_occurrences": 1,
            "body_paragraph_texts": [
                "Body text before the text box.",
                "Body text after the text box.",
            ],
            "drawing_form": "plain w:drawing + wps (no mc:AlternateContent fallback)",
        },
    ),
    "generated/feature-isolated/footnotes-endnotes.docx": sidecar(
        "footnotes-endnotes.docx",
        GENERATED_PROVENANCE,
        NOTES_FEATURES,
        FOOTNOTES_GROUND_TRUTH,
    ),
    "generated/feature-isolated/header-footer-sections.docx": sidecar(
        "header-footer-sections.docx",
        GENERATED_PROVENANCE,
        HDRFTR_FEATURES,
        HDRFTR_GROUND_TRUTH,
    ),
    "generated/feature-isolated/table-merged-nested.docx": sidecar(
        "table-merged-nested.docx",
        GENERATED_PROVENANCE,
        TABLE_FEATURES,
        TABLE_GROUND_TRUTH,
    ),
    "generated/feature-isolated/numbering-custom.docx": sidecar(
        "numbering-custom.docx",
        GENERATED_PROVENANCE,
        NUMBERING_FEATURES,
        NUMBERING_GROUND_TRUTH,
    ),
    "generated/feature-isolated/fragmented-runs.docx": sidecar(
        "fragmented-runs.docx",
        GENERATED_PROVENANCE,
        FRAGMENTED_FEATURES,
        FRAGMENTED_GROUND_TRUTH,
    ),
    "generated/feature-isolated/tracked-moves.docx": sidecar(
        "tracked-moves.docx",
        GENERATED_PROVENANCE,
        MOVES_FEATURES,
        MOVES_GROUND_TRUTH,
    ),
    "generated/feature-isolated/format-changes.docx": sidecar(
        "format-changes.docx",
        GENERATED_PROVENANCE,
        FORMAT_CHANGE_FEATURES,
        FORMAT_CHANGES_GROUND_TRUTH,
    ),
    "generated/feature-isolated/fields.docx": sidecar(
        "fields.docx",
        GENERATED_PROVENANCE,
        FIELDS_FEATURES,
        FIELDS_GROUND_TRUTH,
    ),
    "generated/feature-isolated/placeholder-control.docx": sidecar(
        "placeholder-control.docx",
        GENERATED_PROVENANCE,
        PLACEHOLDER_FEATURES,
        PLACEHOLDER_GROUND_TRUTH,
    ),
    "generated/feature-isolated/bookmarks.docx": sidecar(
        "bookmarks.docx",
        GENERATED_PROVENANCE,
        BOOKMARK_FEATURES,
        BOOKMARKS_GROUND_TRUTH,
    ),
    "generated/feature-isolated/noisy-markup.docx": sidecar(
        "noisy-markup.docx",
        GENERATED_PROVENANCE,
        NOISY_FEATURES,
        NOISY_MARKUP_GROUND_TRUTH,
    ),
    "generated/feature-isolated/toc-field.docx": sidecar(
        "toc-field.docx",
        GENERATED_PROVENANCE,
        TOC_FIELD_FEATURES,
        TOC_FIELD_GROUND_TRUTH,
    ),
    "generated/feature-isolated/row-revisions.docx": sidecar(
        "row-revisions.docx",
        GENERATED_PROVENANCE,
        ROW_REVISION_FEATURES,
        ROW_REVISIONS_GROUND_TRUTH,
    ),
    "generated/feature-isolated/format-changes-rich.docx": sidecar(
        "format-changes-rich.docx",
        GENERATED_PROVENANCE,
        RICH_FORMAT_FEATURES,
        FORMAT_CHANGES_RICH_GROUND_TRUTH,
    ),
    "generated/feature-isolated/paragraph-merge.docx": sidecar(
        "paragraph-merge.docx",
        GENERATED_PROVENANCE,
        MERGE_FEATURES,
        PARAGRAPH_MERGE_GROUND_TRUTH,
    ),
    "generated/feature-isolated/protected-forms.docx": sidecar(
        "protected-forms.docx",
        GENERATED_PROVENANCE,
        ["document-protection", "restrict-editing", "forms-protection"],
        protection_ground_truth("forms"),
    ),
    "generated/feature-isolated/protected-readonly.docx": sidecar(
        "protected-readonly.docx",
        GENERATED_PROVENANCE,
        ["document-protection", "restrict-editing", "read-only-protection"],
        protection_ground_truth("readOnly"),
    ),
    "generated/feature-isolated/protected-tracked.docx": sidecar(
        "protected-tracked.docx",
        GENERATED_PROVENANCE,
        ["document-protection", "restrict-editing", "tracked-changes-protection"],
        protection_ground_truth("trackedChanges"),
    ),
    # -- redline bucket (document-pair ground truth) -------------------------
    "generated/redline/multiround.docx": sidecar(
        "multiround.docx",
        GENERATED_PROVENANCE,
        sorted(
            set(
                MOVES_FEATURES
                + RICH_FORMAT_FEATURES
                + ROW_REVISION_FEATURES
                + MERGE_FEATURES
                + ["two-authors", "comment-inside-insertion", "multi-round-redline"]
            )
        ),
        MULTIROUND_GROUND_TRUTH,
    ),
    "generated/redline/multiround-accepted.docx": sidecar(
        "multiround-accepted.docx",
        GENERATED_PROVENANCE,
        ["redline-resolution-ground-truth", "no-revisions"],
        MULTIROUND_ACCEPTED_GROUND_TRUTH,
    ),
    "generated/redline/compare-original.docx": sidecar(
        "compare-original.docx",
        GENERATED_PROVENANCE,
        ["compare-pair", "clean-no-revisions", "headings", "table"],
        COMPARE_ORIGINAL_GROUND_TRUTH,
    ),
    "generated/redline/compare-revised.docx": sidecar(
        "compare-revised.docx",
        GENERATED_PROVENANCE,
        ["compare-pair", "clean-no-revisions", "headings", "table"],
        COMPARE_REVISED_GROUND_TRUTH,
    ),
    "generated/gauntlet/gauntlet.docx": sidecar(
        "gauntlet.docx",
        GENERATED_PROVENANCE,
        sorted(
            set(
                TRACKED_FEATURES
                + COMMENT_FEATURES
                + SDT_FEATURES
                + TEXTBOX_FEATURES
                + NOTES_FEATURES
                + HDRFTR_FEATURES
                + TABLE_FEATURES
                + NUMBERING_FEATURES
                + FRAGMENTED_FEATURES
                + MOVES_FEATURES
                + RICH_FORMAT_FEATURES
                + ROW_REVISION_FEATURES
                + MERGE_FEATURES
                + FIELDS_FEATURES
                + PLACEHOLDER_FEATURES
                + BOOKMARK_FEATURES
                + ["proof-err", "gauntlet"]
            )
        ),
        {
            "tracked": TRACKED_GROUND_TRUTH,
            "comments": [
                {
                    "author": "Alice Editor",
                    "initials": "AE",
                    "date": "2026-06-03T10:15:00Z",
                    "text": "Gauntlet comment one.",
                    "anchor_paragraph_text": "This gauntlet paragraph carries a comment.",
                }
            ],
            "content_controls": {**CONTENT_CONTROL_GROUND_TRUTH, "sdt_count": 3},
            "textbox_visible_texts": ["Text living inside the text box."],
            "notes": FOOTNOTES_GROUND_TRUTH,
            "moves": MOVES_GROUND_TRUTH,
            "format_changes": {**FORMAT_CHANGES_GROUND_TRUTH, "format_change_count": 5},
            "format_changes_rich": FORMAT_CHANGES_RICH_GROUND_TRUTH,
            "row_revisions": ROW_REVISIONS_GROUND_TRUTH,
            "paragraph_marks": PARAGRAPH_MERGE_GROUND_TRUTH,
            "fields": {**FIELDS_GROUND_TRUTH, "field_count": 3},
            "toc_field": TOC_FIELD_GROUND_TRUTH,
            "placeholder_control": PLACEHOLDER_GROUND_TRUTH,
            "bookmarks": BOOKMARKS_GROUND_TRUTH,
            "proof_err_count": 2,
            "sections": {
                "section_count": 2,
                "header_texts": [
                    "Gauntlet header, section one",
                    "Gauntlet first-page header",
                    "Gauntlet header, section two",
                ],
                "footer_texts": ["Gauntlet footer, section one"],
                "different_first_page_section1": True,
            },
            "table": TABLE_GROUND_TRUTH,
            "numbering": {
                "num_id": 42,
                "numbered_paragraph_texts": [
                    "Gauntlet numbered item one",
                    "Gauntlet numbered item two",
                ],
            },
            "fragmented": {"rate_paragraph_text": RATE_TEXT, "run_count": 8},
        },
    ),
    "generated/large/large-5000-paragraphs.docx": sidecar(
        "large-5000-paragraphs.docx",
        GENERATED_PROVENANCE,
        ["large", "perf-smoke"],
        {
            "body_paragraph_count": 5020,
            "filler_paragraph_count": 5000,
            "heading_count": 20,
            "heading_style": "Heading2",
        },
    ),
    "generated/corrupt/broken-rel.docx": sidecar(
        "broken-rel.docx",
        GENERATED_PROVENANCE,
        ["corrupt-by-construction", "broken-relationship-target"],
        {
            "defect": (
                "word/_rels/document.xml.rels contains dangling relationship rId99"
                " (image) -> word/media/missing-image.png"
            ),
            "expected_finding": "broken_relationship_target",
            "otherwise": "identical to minimal.docx; all XML parses",
            "negative_test_only": True,
        },
    ),
    "generated/corrupt/malformed-xml.docx": sidecar(
        "malformed-xml.docx",
        GENERATED_PROVENANCE,
        ["corrupt-by-construction", "malformed-xml"],
        {
            "defect": "word/document.xml truncated by 40 bytes (unparseable XML)",
            "expected_finding": "unparseable_xml_part",
            "otherwise": "identical to minimal.docx",
            "negative_test_only": True,
        },
    ),
    # -- libreoffice bucket (round-trips; LibreOffice re-authored the XML) ---
    "libreoffice/feature-isolated/tracked-ins-del.docx": sidecar(
        "tracked-ins-del.docx",
        lo_provenance("tracked-ins-del", "Authors, dates and delText survived verbatim."),
        TRACKED_FEATURES,
        TRACKED_GROUND_TRUTH,
    ),
    "libreoffice/feature-isolated/comments.docx": sidecar(
        "comments.docx",
        lo_provenance("comments", "Comment authors, dates and texts survived verbatim."),
        COMMENT_FEATURES,
        COMMENTS_GROUND_TRUTH,
    ),
    "libreoffice/feature-isolated/content-control.docx": sidecar(
        "content-control.docx",
        lo_provenance("content-control", "Both controls and their aliases survived."),
        SDT_FEATURES,
        CONTENT_CONTROL_GROUND_TRUTH,
    ),
    "libreoffice/feature-isolated/textbox.docx": sidecar(
        "textbox.docx",
        lo_provenance(
            "textbox",
            "LibreOffice wrapped the shape in mc:AlternateContent with a VML fallback,"
            " so w:txbxContent occurs TWICE in raw XML for one visible text box —"
            " traversal must not double-count it.",
        ),
        TEXTBOX_FEATURES + ["mc-alternate-content", "vml-fallback"],
        {
            "textbox_visible_texts": ["Text living inside the text box."],
            "raw_txbx_content_occurrences": 2,
            "body_paragraph_texts": [
                "Body text before the text box.",
                "Body text after the text box.",
            ],
            "drawing_form": "mc:AlternateContent (wps choice + VML w:pict fallback)",
        },
    ),
    "libreoffice/feature-isolated/footnotes-endnotes.docx": sidecar(
        "footnotes-endnotes.docx",
        lo_provenance(
            "footnotes-endnotes",
            "LibreOffice renumbered the notes to id 2 and re-segmented the note"
            " body so the leading preserved space rides in its own w:t node;"
            " the visible text is unchanged, leading space included.",
        ),
        NOTES_FEATURES,
        {
            "footnote": {"id": 2, "text": " The footnote body text, hand-authored."},
            "endnote": {"id": 2, "text": " The endnote body text, hand-authored."},
            "note_texts_start_with_preserved_space": True,
            "leading_space_in_own_wt_node": True,
            "reference_paragraph_texts": [
                "This sentence carries a footnote reference.",
                "This sentence carries an endnote reference.",
            ],
        },
    ),
    "libreoffice/feature-isolated/header-footer-sections.docx": sidecar(
        "header-footer-sections.docx",
        lo_provenance(
            "header-footer-sections",
            "LibreOffice exported twelve header/footer parts, most empty, and"
            " duplicated the first-page header definition.",
        ),
        HDRFTR_FEATURES,
        {
            "section_count": 2,
            "nonempty_header_texts_sorted": [
                "First-page header for section one",
                "First-page header for section one",
                "Header for section one",
                "Header for section two",
            ],
            "nonempty_footer_texts_sorted": [
                "Footer for section one",
                "Footer for section two",
            ],
            "header_footer_part_count": 12,
            "different_first_page_section1": True,
        },
    ),
    "libreoffice/feature-isolated/table-merged-nested.docx": sidecar(
        "table-merged-nested.docx",
        lo_provenance("table-merged-nested", "Merge structure survived exactly."),
        TABLE_FEATURES,
        TABLE_GROUND_TRUTH,
    ),
    "libreoffice/feature-isolated/numbering-custom.docx": sidecar(
        "numbering-custom.docx",
        lo_provenance(
            "numbering-custom",
            "LibreOffice rebuilt numbering.xml and remapped the custom definition"
            " from numId 42 to numId 7.",
        ),
        NUMBERING_FEATURES,
        {
            "custom_definition": {"num_id": 7},
            "numbered_paragraphs": [
                {"text": "First numbered item", "ilvl": 0, "num_id": 7},
                {"text": "Second numbered item", "ilvl": 0, "num_id": 7},
                {"text": "Nested lettered item", "ilvl": 1, "num_id": 7},
            ],
        },
    ),
    "libreoffice/feature-isolated/fragmented-runs.docx": sidecar(
        "fragmented-runs.docx",
        lo_provenance(
            "fragmented-runs",
            "LibreOffice merged same-format adjacent runs: 8 runs became 5;"
            " visible text survived verbatim including all special characters.",
        ),
        FRAGMENTED_FEATURES,
        {
            "rate_paragraph": {"text": RATE_TEXT, "run_count": 5},
            "nbsp_paragraph_text": NBSP_TEXT,
        },
    ),
}


def main() -> int:
    for relpath, payload in sorted(SIDECARS.items()):
        docx_path = FIXTURES_DIR / relpath
        assert docx_path.is_file(), f"fixture missing for sidecar: {relpath}"
        sidecar_file = docx_path.with_suffix(".json")
        sidecar_file.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(f"wrote {sidecar_file.relative_to(FIXTURES_DIR)}")
    docx_count = len(list(FIXTURES_DIR.rglob("*.docx")))
    assert docx_count == len(SIDECARS), (
        f"{docx_count} fixtures on disk but {len(SIDECARS)} sidecars defined"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
