"""MANIFEST.sha256 reading/verification for the frozen fixture corpus.

Format is `shasum -a 256`-compatible: one `<hex-digest>  <relative-path>` line
per file, sorted by path, covering every file under `tests/paper/fixtures/`
(both `.docx` fixtures and their `.json` sidecars) except the manifest itself.

Fixtures are frozen: tests fail if any hash changes. Fixtures are never
regenerated by code under test; a new or changed fixture means editing the
manifest in the same reviewed PR (CONVENTIONS §4).
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Dict

from .paths import FIXTURES_DIR, iter_manifest_covered_paths

MANIFEST_PATH = FIXTURES_DIR / "MANIFEST.sha256"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_manifest(path: Path = MANIFEST_PATH) -> Dict[str, str]:
    """{relative-path: hex-digest} parsed from the manifest file."""
    entries: Dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line:
            continue
        digest, _, relpath = line.partition("  ")
        if len(digest) != 64 or not relpath:
            raise ValueError(f"{path}:{line_number}: malformed manifest line {raw_line!r}")
        if relpath in entries:
            raise ValueError(f"{path}:{line_number}: duplicate manifest entry {relpath!r}")
        entries[relpath] = digest
    return entries


def compute_manifest() -> Dict[str, str]:
    """{relative-path: hex-digest} for the current on-disk fixture corpus."""
    return {
        path.relative_to(FIXTURES_DIR).as_posix(): sha256_file(path)
        for path in iter_manifest_covered_paths()
    }


def render_manifest(entries: Dict[str, str]) -> str:
    """Serialize `entries` in the canonical manifest format (sorted, trailing NL)."""
    lines = [f"{digest}  {relpath}" for relpath, digest in sorted(entries.items())]
    return "\n".join(lines) + "\n"
