"""Freeze tests for the fixture corpus: manifest coverage, hashes, sidecars."""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any, Dict

import pytest

from .harness.manifest import MANIFEST_PATH, compute_manifest, read_manifest
from .harness.paths import (
    FIXTURES_DIR,
    PROVENANCE_BUCKETS,
    TAXONOMY_BUCKETS,
    iter_fixture_docx_paths,
    sidecar_path,
)

SIDECAR_KEYS = ("fixture", "provenance", "features", "ground_truth", "verified_by", "date")
PROVENANCE_KEYS = ("app", "version", "notes")


def _relpaths(paths) -> list:
    return [p.relative_to(FIXTURES_DIR).as_posix() for p in paths]


class DescribeFixtureManifest:
    """Every fixture's SHA-256 is frozen; drift fails the suite."""

    def it_exists(self):
        assert MANIFEST_PATH.is_file(), "tests/paper/fixtures/MANIFEST.sha256 is missing"

    def it_covers_exactly_the_on_disk_corpus(self):
        frozen = set(read_manifest())
        on_disk = set(compute_manifest())
        missing_from_manifest = sorted(on_disk - frozen)
        gone_from_disk = sorted(frozen - on_disk)
        assert not missing_from_manifest, (
            f"files not frozen in MANIFEST.sha256: {missing_from_manifest};"
            " run fixtures_authoring/freeze_manifest.py deliberately and review the diff"
        )
        assert not gone_from_disk, f"frozen files missing from disk: {gone_from_disk}"

    def it_matches_the_sha256_of_every_frozen_file(self):
        frozen = read_manifest()
        current = compute_manifest()
        drifted = sorted(
            relpath
            for relpath, digest in frozen.items()
            if current.get(relpath) != digest
        )
        assert not drifted, (
            f"fixture hash drift detected (fixtures are frozen): {drifted};"
            " fixtures are never regenerated by code under test"
        )


class DescribeFixtureLayout:
    def it_keeps_every_fixture_in_a_known_provenance_bucket(self):
        strays = [
            rel
            for rel in _relpaths(iter_fixture_docx_paths())
            if rel.split("/")[0] not in PROVENANCE_BUCKETS
        ]
        assert not strays, f"fixtures outside provenance buckets: {strays}"

    def it_keeps_every_fixture_in_a_known_taxonomy_bucket(self):
        strays = [
            rel
            for rel in _relpaths(iter_fixture_docx_paths())
            if len(rel.split("/")) != 3 or rel.split("/")[1] not in TAXONOMY_BUCKETS
        ]
        assert not strays, f"fixtures outside taxonomy buckets: {strays}"

    def it_pairs_every_docx_with_a_sidecar_and_vice_versa(self):
        missing_sidecars = [
            rel
            for rel, docx_path in zip(
                _relpaths(iter_fixture_docx_paths()), iter_fixture_docx_paths()
            )
            if not sidecar_path(docx_path).is_file()
        ]
        orphan_sidecars = [
            rel
            for rel, json_path in (
                (p.relative_to(FIXTURES_DIR).as_posix(), p)
                for p in sorted(FIXTURES_DIR.rglob("*.json"))
            )
            if not json_path.with_suffix(".docx").is_file()
        ]
        assert not missing_sidecars, f"fixtures without sidecars: {missing_sidecars}"
        assert not orphan_sidecars, f"sidecars without fixtures: {orphan_sidecars}"


def _sidecars() -> Dict[str, Dict[str, Any]]:
    return {
        p.relative_to(FIXTURES_DIR).as_posix(): json.loads(
            sidecar_path(p).read_text(encoding="utf-8")
        )
        for p in iter_fixture_docx_paths()
    }


class DescribeSidecars:
    """The sidecar schema is pinned — exactly these keys."""

    @pytest.fixture
    def sidecars(self) -> Dict[str, Dict[str, Any]]:
        return _sidecars()

    def it_conforms_to_the_pinned_schema(self, sidecars: Dict[str, Dict[str, Any]]):
        for rel, payload in sidecars.items():
            assert tuple(payload.keys()) == SIDECAR_KEYS, (
                f"{rel}: sidecar keys {tuple(payload.keys())} != pinned {SIDECAR_KEYS}"
            )
            assert tuple(payload["provenance"].keys()) == PROVENANCE_KEYS, rel
            assert isinstance(payload["features"], list) and payload["features"], rel
            assert all(isinstance(f, str) for f in payload["features"]), rel
            assert isinstance(payload["ground_truth"], dict) and payload["ground_truth"], rel
            assert isinstance(payload["verified_by"], str) and payload["verified_by"], rel
            dt.date.fromisoformat(payload["date"])  # raises on malformed date

    def its_fixture_field_matches_the_docx_filename(
        self, sidecars: Dict[str, Dict[str, Any]]
    ):
        mismatched = [
            rel for rel, payload in sidecars.items() if payload["fixture"] != Path(rel).name
        ]
        assert not mismatched, f"sidecar 'fixture' field mismatches: {mismatched}"

    def its_provenance_app_is_honest_about_its_bucket(
        self, sidecars: Dict[str, Dict[str, Any]]
    ):
        """A file is labeled with the application that actually wrote its bytes."""
        expectations = {
            "generated": "build_fixtures.py",
            "libreoffice": "LibreOffice",
            "word": "Word",
            "google": "Google",
        }
        for rel, payload in sidecars.items():
            bucket = rel.split("/")[0]
            needle = expectations.get(bucket)
            if needle is not None:
                assert needle in payload["provenance"]["app"], (
                    f"{rel}: provenance app {payload['provenance']['app']!r}"
                    f" does not match its {bucket!r} bucket"
                )
